### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mpaul31** [Meyce/Core-Rebus-WebJob#2]
Just out of curiosity, who/what calls the Start method on the bus?

_sorry not an issue_

**Comment by Meyce** [comment]
The bus is started when it is created by the container in the IHostedService.

https://github.com/Meyce/Core-Rebus-WebJob/blob/d95eac1c20ec66ed09859040b829c6d27d2081de/CoreRebusWebJobHandlerService/HandlerService.cs#L39

**Comment by mpaul31** [comment]
gotcha i saw that comment, i just expected to manually see a call to the Start method somewhere.

**Comment by mpaul31** [comment]
got it. went digging in the ServiceProvider repo and saw the call during AddBus
